; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = 
  pio_addr2line.ini

[esp32_common]
	platform = espressif32
	framework = arduino
	upload_speed = 921600
	monitor_speed = 115200
	build_type = release
	build_flags = 
		-D LOG_ERROR_ENABLED
		-D LOG_WARN_ENABLED
		-D LOG_INFO_ENABLED
	lib_extra_dirs = 
		./lib/system
		./lib/net
	extra_scripts =
		post:pio_addr2line.py
	lib_deps =
		lib_utils
		lib_net

[esp32_common_dbg]
	extends = esp32_common
;	debug build not required without debugger
;	build_type = debug
	build_flags = 
		${esp32_common.build_flags}
		-D LOG_WEB_DBG_ENABLED
		-D LOG_WIFI_DBG_ENABLED
		-D LOG_DEBUG_ENABLED
		-D LOG_MSG_ENABLED

[env:wemos_d1_mini32_rel]
	board = wemos_d1_mini32
	extends = esp32_common

[env:wemos_d1_mini32_dbg]
	board = wemos_d1_mini32
	extends = esp32_common_dbg

[env:devkit_v4_rel]
	board = az-delivery-devkit-v4
	extends = esp32_common

[env:devkit_v4_dbg]
	board = az-delivery-devkit-v4
	extends = esp32_common_dbg

