; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = 
  pio_addr2line.ini

[esp32_common]
	platform = espressif32
	framework = arduino
	upload_speed = 921600
	monitor_speed = 115200
	build_flags = 
		-D RFS_USE_SPIFFS
		-D LOG_WEB_DBG_ENABLED
		-D LOG_WIFI_DBG_ENABLED
		-D LOG_ERROR_ENABLED 
		-D LOG_WARN_ENABLED 
		-D LOG_INFO_ENABLED 
		-D LOG_DEBUG_ENABLED 
		-D LOG_MSG_ENABLED 
	lib_extra_dirs = 
   		./lib/io
   		./lib/system
   		./lib/net
   		./lib/web
	lib_deps =
		lib_http_server
		lib_settings
		lib_net
		Preferences
		esphome/ESPAsyncWebServer-esphome @ ^3.2.0
		bblanchon/ArduinoJson @ ^7.0.4
		ropg/ezTime @ ^0.8.3
	test_framework = unity  

[env:wemos_d1_mini32]
	board = wemos_d1_mini32
	extends = esp32_common

